# Site settings
title: "12-Tech Portfolio"
email: 'your-email@example.com'
description: "Software developer and designer. Creating useful things for the web."
baseurl: "" # Leave it empty for root path
url: "https://12-tech.github.io" # Use your GitHub Pages URL
twitter_username: 'your-twitter-handle'
github_username: '12-tech'
medium_username: 'your-medium-username' # (if you have one)

# Build settings
markdown: kramdown
theme: "phantom" # Uncommented to use Phantom theme
plugins:
  - jekyll-paginate

# Pagination settings
paginate: 10
paginate_path: "/page:num/"

pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

### Phantom settings
footer_text: '© 2025 12-Tech. All rights reserved.'
admin_name: 'Your Name'
google_analytics: "" # Leave empty if not using
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
  - { url: '/projects', text: 'Projects' }
  - { url: '/contact', text: 'Contact' }
