# Site settings
title: "Adijat Sulaimon"
email: 'Adijatsulaimon01@gmail.com'
description: "Solving complex problems with technology is my superpower. 
I thrive on dissecting challenges, diving deep into their intricacies, and crafting innovative solutions. 
As a hands-on Embedded Systems Engineer, 
I blend technical expertise with a relentless curiosity for learning, 
whether it’s mastering new tools or exploring cutting-edge methodologies. Don’t just take my word for it; 
explore my featured projects below to see how I turn ideas into impact.
"
baseurl: "" # Leave it empty for root path
url: "https://12-tech.github.io" # Use your GitHub Pages URL
email: 'Adijatsulaimon01@gmail.com'
github_username: '12-tech'
linkedln: 'https://www.linkedin.com/in/adijat01/' # (if you have one)

# Build settings
markdown: kramdown
theme: minima
 # Uncommented to use Phantom theme
plugins:
  - jekyll-paginate

# Pagination settings
paginate: 10
paginate_path: "/page:num/"

pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

### Phantom settings
footer_text: '© 2025 12-Tech. All rights reserved.'
admin_name: 'Adijat Ajoke Sulaimon'
google_analytics: "" # Leave empty if not using
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
  - { url: '/projects', text: 'Projects' }
  - { url: '/contact', text: 'Contact' }
