# Site settings
title: "Hello. I'm Jami Gibbs."
email: 'jami0821@gmail.com'
description: "I'm a software developer and designer from Chicago creating useful things for the web."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://12-tech.github.io" # Update this to your GitHub Pages URL
twitter_username: 'jamigibbs'
github_username: 'jamigibbs'
medium_username: 'blog.jamigibbs.com'

# Build settings
markdown: kramdown
theme: "phantom" # Uncommented to use Phantom theme
plugins:
  - jekyll-paginate

# Pagination settings (adjust if you have posts)
paginate: 10
paginate_path: "/page:num/"

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

### Phantom settings
footer_text: '© 2018 Jami Gibbs'
admin_name: 'Jami Gibbs'
google_analytics: "UA-9999999-99" # Update with your own tracking ID or remove if not using
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
